### ISSUE TITLE
Estados: backend

### ISSUE THREAD

**Issue by Azowyl** [TDP2-Lucas-3/contame-backend#67]
Tenemos que hacer el sistema de estados, que permita, mostrar y cambiarlo

Tenemos que definir una lista de estados y **transiciones**, es decir, desde un estado actual X a qué estados Y se va poder transicionar

Debería haber una API que sea "incidents/id/state/ para el POST y incidents/id/state/transitions para listar qué transicoines son válidas para el estado actual, creo que eso es lo más flexible

**Comment by MatiasReimondo** [comment]
Inverti 6 horas en ese issue. No esta cerrado todavia.
Falta actualizacion grupal

**Comment by MatiasReimondo** [comment]
Inverti 3 horas en este issue. Actualizacion grupal y get de estados dependiendo del estado.
Falta integracion
