### ISSUE TITLE
Agrupaciones de incidencias

### ISSUE THREAD

**Issue by lucaslavandeira** [TDP2-Lucas-3/contame-backend#70]
Cada incidencia puede tener hasta 1 padre asociado

Una incidencia que tiene incidencias hijas no puede tener incidencia padre (es decir, no puede haber incidencias abuelas)

Al cambiarse el estado de una incidencia padre, se deben modificar también el estado de todas las incidencias hijas

**Comment by MatiasReimondo** [comment]
Inverti 6 horas ne ese issue. Falta su integracion
